algoritmo "exercício 14"
 //Ler um valor e escrever a mensagem É MAIOR QUE 10!
// se o valor lido for maior que 10, caso
//contrário escrever NÃO É MAIOR QUE 10!
var
 numero: inteiro
inicio


Escreval ("Informe o valor número inteiro:")

leia (numero)

se numero > 10 entao

escreva ("O número informado é maior que 10 ")

senao

escreva ("O número informado não é Maior que 10 ")

fimse
fimalgoritmo
